development:
  adapter: postgresql
  database: db/hoover_island_development
  host: localhost

test:
  adapter: postgresql
  database: db/hoover_island_test
  host: localhost

production:
  adapter: postgresql
  database: db/hoover_island_production
  host: localhost
