development:
  adapter: postgresql
  database: db/development
  host: localhost

test:
  adapter: postgresql
  database: db/test
  host: localhost

production:
  adapter: postgresql
  database: db/production
  host: localhost
